[package]
org = "wso2"
name = "document_search"
version = "0.1.0"
distribution = "2201.9.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="azure.ai.search.index"
version="1.0.0"
repository="local"
