[package]
distribution = "2201.9.3"
org = "ballerinax"
name = "azure.ai.search.index"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Search", "Azure", "Search Index", "Azure AI Search"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.ai.search.index"

[build-options]
observabilityIncluded = true
